export const BREADCRUMB_LABELS: Record<string, string> = {
  "/": "خانه",
  "athlete-list": "لیست ورزشکاران",
  "athlete-files": "لیست فایل های ورزشکاران",
  "athlete-details": "اطلاعات ورزشکار",
  "person-list": "لیست افراد",
  "person-files": "فایل های افراد",
  "person-details": "اطلاعات فرد",
  "athlete-insurance-list": "لیست بیمه ورزشکاران",
  "athlete-insurance-expiring": "بیمه های نزدیک به انقضا",
  courses: "لیست دوره های آموزشی",
  "course-register": "ثبت نام ورزش آموز جدید",
  "course-details": "منوی دسترسی ",
  installment: "لیست اقساط",
  "installment-items": "لیست آیتم‌های قسط",
  "online-transactions": "لیست تراکنش های آنلاین",
  "transaction-details": "جزئیات تراکنش",
  "report-course-list": "لیست دوره‌های آموزشی",
  "report-course-details": "جزئیات گزارش مالی دوره",
  "athlete-wallet": "لیست کیف پول ورزشکاران",
  "person-wallet": "لیست کیف پول افراد",
  "athlete-introducing-charge": "پاداش معرفی (ورزشکاران)",
  "person-introducing-charge": "پاداش معرفی (افراد)",
  "special-wallet": "لیست کیف پول‌های ویژه",
  "public-messages": "لیست پیام‌های عمومی",
  "message-details": "جزئیات پیام",
  "private-messages": "لیست پیام‌های خصوصی",
  sms: "لیست پیامک‌ها",
};
