export const SIDEBAR_ITEM_LINKS = {
  home: "/",
  athleteList: "/athlete-list",
  athleteFiles: "/athlete-list/athlete-files",
  personList: "/person-list",
  personFiles: "/person-list/person-files",
  athleteInsuranceList: "/athlete-insurance-list",
  athleteInsuranceExpiring:
    "/athlete-insurance-list/athlete-insurance-expiring",
  courses: "/courses",
  courseRegister: "/courses/course-register",
  installment: "/installment",
  installmentOnlineTransactions: "/installment/online-transactions",
  installmentReportCourseList: "/installment/report-course-list",
  athleteWallet: "/wallet/athlete-wallet",
  personWallet: "/wallet/person-wallet",
  athleteIntroducingCharge: "/wallet/athlete-introducing-charge",
  personIntroducingCharge: "/wallet/person-introducing-charge",
  specialWallet: "/wallet/special-wallet",
  publicMessages: "/messages/public-messages",
  privateMessages: "/messages/private-messages",
  sms: "/messages/sms",
};
