export const SIDEBAR_ICON_NAMES: Record<string, string> = {
  "/": "Home",
  "athlete-list": "/icon/ic-athlete.png",
  "athlete-files": "/icon/ic-file.png",
  "athlete-details": "/icon/ic-athlete.png",
  "person-list": "/icon/ic-user.png",
  "person-files": "/icon/ic-file.png",
  "person-details": "/icon/ic-file.png",
  "athlete-insurance-list": "/icon/ic-athlete.png",
  "athlete-insurance-expiring": "/icon/ic-athlete.png",
  courses: "/icon/ic-course.png",
  "course-register": "/icon/ic-athlete.png",
  "course-details": "/icon/ic-course.png",
  installment: "/icon/ic-payment.png",
  "installment-items": "/icon/ic-payment.png",
  "online-transactions": "/icon/ic-online-payment.png",
  "transaction-details": "/icon/ic-online-payment.png",
  "report-course-list": "/icon/ic-course.png",
  "report-course-details": "/icon/ic-chart.png"
};
