import type { Metadata } from "next";
import { DirectionProvider } from "@/components/ui/direction";
import { vazir } from "@/fonts";
import { AuthProvider } from "@/context/AuthProvider";
import { cn } from "@/lib/utils";
import { ViewTransitions } from "next-view-transitions";
import ToastContainer from "@/components/toast/ToastContainer";
import { ToastProvider } from "@/context/ToastContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "کیا اسپورت",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={cn(vazir.variable)}>
      <body>
        <AuthProvider>
          <DirectionProvider direction="rtl">
            <div className="relative flex h-dvh w-full">
              <ViewTransitions>
                <ToastProvider>
                  {children}
                  <ToastContainer />
                </ToastProvider>
              </ViewTransitions>
            </div>
          </DirectionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
