import { FormConfig } from "@/components/formBuilder/types";

export const athleteListFormConfig: FormConfig = [
  {
    id: "basic-info",
    type: "section",
    title: "اطلاعات پایه",
    icon: "User2",
    wrapperVariant: "card",
    headerClassName: "text-rose-400",
    children: [
      {
        id: "firstName",
        label: "نام",
        type: "text",
        required: true,
        colSpan: 6,
      },
      {
        id: "lastName",
        label: "نام خانوادگی",
        type: "text",
        required: true,
        colSpan: 6,
      },
      {
        id: "fatherName",
        label: "نام پدر",
        type: "text",
        required: true,
        colSpan: 6,
      },
      {
        id: "nationalCode",
        label: "کد ملی",
        type: "nationalcode",
        required: true,
        colSpan: 6,
        maxLength: 10,
      },
      {
        id: "gender",
        label: "جنسیت",
        type: "select",
        options: [
          {
            value: "1",
            label: "خانم",
          },
          {
            value: "2",
            label: "آقا",
          },
        ],
        required: true,
        colSpan: 6,
      },
      {
        id: "birthDate",
        label: "تاریخ تولد",
        type: "date",
        required: true,
        colSpan: 6,
      },
      {
        id: "personelImage",
        label: "عکس پرسنلی",
        type: "image",
        required: true,
        colSpan: 6,
      },
    ],
  },
  {
    id: "call-info",
    type: "section",
    title: "اطلاعات تماس",
    icon: "Phone",
    wrapperVariant: "card",
    headerClassName: "text-blue-400",
    children: [
      {
        id: "phone",
        label: "تلفن ثابت",
        type: "phone",
        required: true,
        colSpan: 6,
      },
      {
        id: "phone2",
        label: "تلفن ثابت (۲)",
        type: "phone",
        colSpan: 6,
      },
      {
        id: "mobile",
        label: "تلفن همراه",
        type: "mobile",
        required: true,
        colSpan: 6,
      },
      {
        id: "email",
        label: "ایمیل",
        type: "email",
        colSpan: 6,
      },
      {
        id: "parentPhone",
        label: "تلفن ثابت ولی",
        type: "phone",
        colSpan: 6,
      },
      {
        id: "parentMobile",
        label: "تلفن همراه ولی",
        type: "mobile",
        colSpan: 6,
      },
      {
        id: "address",
        label: "آدرس",
        type: "textarea",
        required: true,
        colSpan: 12,
      },
    ],
  },
  {
    id: "athleticBackground",
    type: "section",
    title: "سابقه ورزشی",
    icon: "Volleyball",
    wrapperVariant: "card",
    headerClassName: "text-green-500",
    children: [
      {
        id: "athleticBackground",
        label: "سابقه ورزشی",
        type: "textarea",
      },
    ],
  },
  {
    id: "familiar",
    type: "section",
    title: "آشنایی با موسسه",
    icon: "Newspaper",
    wrapperVariant: "card",
    headerClassName: "text-violet-500",
    children: [
      {
        id: "_",
        label: "نحوه ی آشنایی با موسسه",
        type: "select",
        options: [
          { value: "1", label: "دوستان و آشنایان" },
          { value: "2", label: "شبکه های اجتماعی" },
          { value: "3", label: "اینترنت و سایت" },
          { value: "4", label: "تبلیغات محیطی" },
          { value: "5", label: "معرفی از طریق ارگان ها" },
        ],
        colSpan: 6,
      },
      {
        id: "__",
        label: "معرف",
        type: "text",
        colSpan: 6,
      },
    ],
  },
  {
    id: "Insurance",
    type: "section",
    title: "بیمه",
    icon: "NotebookText",
    wrapperVariant: "card",
    headerClassName: "text-orange-500",
    children: [
      {
        id: "insuranceNumber",
        label: "شماره بیمه",
        type: "text",
        colSpan: 6,
      },
      {
        id: "insuranceDate",
        label: "تاریخ اعتبار بیمه",
        type: "date",
        colSpan: 6,
      },
      {
        id: "insuranceN",
        label: "وضعیت تمدید بیمه",
        type: "select",
        options: [
          { value: "1", label: "پیش فرض" },
          { value: "1", label: "تمدید" },
          { value: "1", label: "انصراف از تمدید" },
        ],
        colSpan: 6,
      },
    ],
  },
  {
    id: "shirtNumber",
    type: "section",
    title: "شماره پیراهن",
    icon: "Shirt",
    wrapperVariant: "card",
    headerClassName: "text-pink-500",
    children: [
      {
        id: "shirtNumber",
        label: "شماره پیراهن",
        type: "number",
        colSpan: 6,
      },
    ],
  },
  {
    id: "password",
    type: "section",
    title: "رمز عبور",
    icon: "Lock",
    wrapperVariant: "card",
    headerClassName: "text-amber-500",
    children: [
      {
        id: "password",
        label: "رمز عبور",
        type: "password",
        colSpan: 6,
      },
      {
        id: "passwordAgain",
        label: "تکرار رمز عبور",
        type: "password",
        colSpan: 6,
      },
    ],
  },
];
